/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProfileImport } from './routes/profile'
import { Route as IndexImport } from './routes/index'
import { Route as ExperiencesIndexImport } from './routes/experiences.index'
import { Route as ExperiencesIdImport } from './routes/experiences.$id'

// Create/Update Routes

const ProfileRoute = ProfileImport.update({
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ExperiencesIndexRoute = ExperiencesIndexImport.update({
  path: '/experiences/',
  getParentRoute: () => rootRoute,
} as any)

const ExperiencesIdRoute = ExperiencesIdImport.update({
  path: '/experiences/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/experiences/$id': {
      id: '/experiences/$id'
      path: '/experiences/$id'
      fullPath: '/experiences/$id'
      preLoaderRoute: typeof ExperiencesIdImport
      parentRoute: typeof rootRoute
    }
    '/experiences/': {
      id: '/experiences/'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  ProfileRoute,
  ExperiencesIdRoute,
  ExperiencesIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/profile",
        "/experiences/$id",
        "/experiences/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/profile": {
      "filePath": "profile.tsx"
    },
    "/experiences/$id": {
      "filePath": "experiences.$id.tsx"
    },
    "/experiences/": {
      "filePath": "experiences.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
